encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name ="search"),
    path("new", views.newpage, name = "newpage"), 
    path("random", views.randpage, name="random"),
    path("<str:title>", views.item, name ="item"),
    path("<str:title>/edit", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import re
import random
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from . import util


#index page with list of all existing entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
    
#view for individual encyclopedia entries
def item(request, title):
    if(util.get_entry(title)):
        item = (util.get_entry(title))
        return render(request, "encyclopedia/item.html", {
            "title": title,
            "item": item
        })
    else: #ERROR CODE_0 page does not exist
        return render(request, "encyclopedia/error.html", {
            "error_code": '0'
        })
    
#function to return search results
def search(request):
    q = request.GET["q"] #receives the term the user searched for
    if(util.get_entry(q)): #if query matches a existing entry, user is taken to the entry page
        return item(request,q)
    else: 
        s = r'.*'+q+r'.*' #regular expression pattern to be searched in each existing entry, pattern matches words that have the user input
        all = '\n'.join(util.list_entries()) #create a unique string with all the existing words separated by newline
        result = re.findall(s,all,re.I) #get a list with every word the regex pattern matched in the string with entries - re.I case makes it case insensitive 
        return render(request,"encyclopedia/search.html", { #render search page with query and list of results
            "term": q, 
            "entries": result
        })
#view to add new entries to the encyclopedia, newpage.html has textareas for title and content
def newpage (request):
    if request.method=="POST": #if the request method is POST it means the user pressed the submit button with the filled form
        title = request.POST["title"] #user input for the title of the page
        content = request.POST["content"] #user input for the content of the page
        if util.get_entry(title): #checks if the title already exists in the wiki
            return render(request, "encyclopedia/error.html", {
                "existing_page": title,
                "error_code": '1'
            })
        else:
            util.save_entry(title,content)
            return item(request,title) #redirects user to the page created
    return render(request, "encyclopedia/newpage.html",{#request method is GET, meaning the user clicked a link to create a new page
        "page_title": '', #textareas for the title and content are blank so the user can fill the and submit the form to create a new page
        "page_content": '',
        "page_url": "newpage"
    })
#view to edit an existing term in the wiki
def edit(request, title):
    if request.method=="POST":
        new_content = request.POST["content"] #user input for the content of the page
        util.save_entry(title,new_content) 
        """
            ADD SOME SERVER-SIDE VALIDATION
        """
        return item(request,title)
    else:
        if(util.get_entry(title)): #checks if the term exists in the wiki
            return render(request, "encyclopedia/newpage.html",{ #renders the same page used to submit a new entry
                "page_title": title, #but pre-populates the textareas with the title and content of the entry the user wants to edit
                "page_content": util.get_entry(title),
                "page_url": "edit"
            })
        else: 
            return render(request, "encyclopedia/error.html", {
                "error_code": '2'
            })
def randpage(request):
    return item(request,random.choice(util.list_entries())) #returns random item from the entries' list
    

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
	<div class="col-lg-10 col-md-9 p-4">
		<h1>Something went wrong.</h1>
		{% if error_code == '0' %}
			This page does not exist.<br>
			You can search for another entry or <a href ="{% url 'wiki:newpage' %}">add a new page.</a>
		{% elif error_code == '1' %}
			The page you tried to create already exists. Click<a href ="{% url 'wiki:item' existing_page %}"> here</a> to check it out.
		{% elif error_code == '2' %}
			The entry you tried to edit does not exist.<br>
			You can search for another entry or <a href ="{% url 'wiki:newpage' %}">add a new page.</a>
		{% else %}
			Return to the <a href= "{% url 'wiki:index' %}">home page.</a>
		{% endif %}
	</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
	<div class="col-lg-10 col-md-9 p-4">
		<h1>All Pages</h1>
		<ul>
			{% for entry in entries %}
				<li><a href="{% url 'wiki:item' entry %}">{{ entry }}</a></li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

encyclopedia/templates/encyclopedia/item.html
{% extends "encyclopedia/layout.html" %}
{% load md2 %} 

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
	<div class="col-lg-10 col-md-9 p-4">
		<div class="col-lg-2 col-sm-3 float-right"><a class="float-right" href="{% url 'wiki:edit' title%}">Edit Page</a></div>
		{{ item|markdown }}
	</div>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
		<style>
			#title{
				width:100%;
				font-size: 18px;
				height:40px;
				resize:none;
			}
			#content{
				white-space: pre-wrap !important;
				width:100%;
				height:350px;
			}
			@media (max-width:768px){
				.sidebar{
					height: auto;
				}
			}
		</style> 
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="GET">
				{% csrf_token%}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href ="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href ="{% url 'wiki:random' %}" >Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
		<div class="col-lg-6 col-md-7 p-4 ">
			{% if page_url == "newpage" %}
				<form action="{% url 'wiki:newpage' %}" method="POST" id="add">
				<h3>New Page</h3>
			{% elif page_url == "edit" %}
				<form action="{% url 'wiki:edit' page_title %}" method="POST" id="add">
				<h3>Edit Page</h3>
			{% endif %}
			{% csrf_token%}
				<textarea id ="title" form="add" name= "title" placeholder="Enter page title" 
					autofocus {% if page_url == "newpage" %} required {% elif page_url == "edit" %} 
					disabled {% endif %}>{{ page_title }}</textarea>
				<textarea id="content" form="add" name= "content" 
					placeholder="Enter page heading and the term definition" 
					required>{{ page_content }}</textarea>
				<div class="float-right"><input type="submit"></div>
				<div class="pt-2 pl-4">
					<h4>Format hints</h4>
					# Page Heading<br>
					**bold text**<br>
					*italic text*<br>
					- unordered list item<br>
					* unordered list item<br>
					1. ordered list item<br>
				</div>
			</form>
		</div>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
	<div class="col-lg-10 col-md-9 p-4">
		{% if entries  %}<h1>Possible matches for {{ term }}: </h1>
			<ul> 
				{% for entry in entries %}
							<li><a href=" {% url 'wiki:item' entry %}">{{ entry }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<h3>Sorry.</h3>
			<p>Your search did not match any entry. Please make sure that all words are spelled correctly.<br>
			Additionally, you can <a href="{% url 'wiki:newpage' %}">create a new page</a>.</p>
		{% endif %}	
	</div> 
{% endblock %}